version: "3.9"
services:
  bot:
    build:
      dockerfile: Dockerfile
      context: BigWillBot
    volumes:
      - ./BigWillBot/app:/code/app
      - ./config.ini:/code/config.ini
    restart: always
  api:
    build:
      dockerfile: Dockerfile
      context: CryptoApi
    volumes:
      - ./CryptoApi/app:/code/app
      - ./config.ini:/code/config.ini
      - ./firebase-project-credentials.json:/code/firebase-project-credentials.json
    restart: always

networks:
  default:
    external:
      name: global-network