version: "3.9"
services:
  bot:
    build:
      dockerfile: Dockerfile
      context: BigWillBot
    volumes:
      - ./BigWillBot/app:/code/app
      - ./config.ini:/code/config.ini
    restart: always
  api:
    build:
      dockerfile: Dockerfile
      context: CryptoApi
    volumes:
      - ./CryptoApi/app:/code/app
      - ./config.ini:/code/config.ini
    ports:
      - "80:80"
    restart: always
